### PR TITLE
Add password reset compatibility

### PR DESCRIPTION
**Pull request by bvangraafeiland**
As discussed in #13. Replacing the ReminderRepository turned out to be more complicated than I thought, for some reason Laravel insisted on sticking with the default one, and I don't know how to replace it. I did finish the code though, so if you're interested just let me know.

Anyway, this way is a bit more consistent with the Laravel documentation (a separate form for resetting the password rather than generating one) while achieving the same goal.

For this to work correctly, one line has to be changed in the generated RemindersController as well. The password reset function just needs this:

``` php
DB::table('users')->where('id', $user->id)->update(['password' => sha1($password)]);
```

### CODE REVIEW

**Comment by bvangraafeiland** [comment]
Just found out how to do the replace thing. I could add it to this PR. The thing is that it won't work with the default generated reminder stuff (and the view that's included with every install), though I suppose I could create proper defaults and put them in the package, so that they can be published through artisan. It would be a bit hacky because the remind email only expects to send a token, to send the password along I'd pass along an array as "token" containing both the token and the generated password.

**Comment by bvangraafeiland** [comment]
I've now also written a bunch of unit tests for your Guard implementation, getting around 94% coverage. If you'd like to have those too, I can include them in the PR (or maybe make a separate one).

**Comment by franzliedke** [comment]
Awesome, please create a separate one for those. Thank you very much!

**Comment by bvangraafeiland** [comment]
Will do, although I don't think it's possible to have multiple open PR's. I'll add it after this one has been closed.

**Comment by franzliedke** [comment]
Oh, it is possible. Just create a new branch starting at my latest commit and send the pull request from that branch.

**Comment by bvangraafeiland** [comment]
Any chance this will be pulled in soon? I kind of need the changes for my project, and although I could of course just modify the vendor version, I'd prefer not to. If you don't much care for the new reminder repository, User.php is really the only file that needs updating.

**Comment by franzliedke** [comment]
Thanks for the reminder. I will review this soon - after my last exam. =)

**Comment by franzliedke** [comment]
Since this uses a trait, this will only work with PHP 5.4, so I can't just merge it into the next 1.0.x release. How should we proceed with this?

**Comment by bvangraafeiland** [comment]
Oh that's easy, the trait only implements a single method, getReminderEmail(), so instead of using the trait, that method can be pasted in the User class.

**Comment by franzliedke** [comment]
Okay, I've implemented the subset, leaving you as the author of [the commit](https://github.com/franzliedke/auth-fluxbb/commit/060da46e74ca59a8c71c42196237972973df56a1).

We might want to add our own controller generator instead of building a custom repository, as FluxBB's way of doing it (generating a password) is not the best way.

Anyway, thank you very much! This is in `@dev` right now, but will be published in a release soon. Please test and report back!

**Pull request closed without merging**
